/**
 * Theme color presets for customizable app themes
 */

export type LightThemePreset = 'default' | 'warmWhite' | 'coolGray' | 'lavender' | 'mint' | 'vscode' | 'intellij' | 'sky';
export type DarkThemePreset = 'trueBlack' | 'defaultDark' | 'deepBlue' | 'darkPurple' | 'forest' | 'vscodeDark' | 'dracula' | 'darkTeal';

interface ColorScheme {
  background: string;
  foreground: string;
  card: string;
  cardForeground: string;
  primary: string;
  primaryForeground: string;
  secondary: string;
  secondaryForeground: string;
  muted: string;
  mutedForeground: string;
  accent: string;
  accentForeground: string;
  destructive: string;
  destructiveForeground: string;
  border: string;
  input: string;
  ring: string;
}

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  colors: ColorScheme;
}

// Light theme presets
export const LIGHT_THEME_PRESETS: Record<LightThemePreset, ThemePreset> = {
  default: {
    id: 'default',
    name: 'Default',
    description: 'Classic clean white',
    colors: {
      background: '#ffffff',
      foreground: '#25262b',
      card: '#ffffff',
      cardForeground: '#25262b',
      primary: '#343a46',
      primaryForeground: '#fcfcfc',
      secondary: '#f5f5f5',
      secondaryForeground: '#343a46',
      muted: '#f5f5f5',
      mutedForeground: '#8e8e93',
      accent: '#f5f5f5',
      accentForeground: '#343a46',
      destructive: '#dc3545',
      destructiveForeground: '#fcfcfc',
      border: '#C0C0C0',
      input: '#EBEBEB',
      ring: '#b5b5b5',
    },
  },
  warmWhite: {
    id: 'warmWhite',
    name: 'Warm White',
    description: 'Cream tint, easy on eyes',
    colors: {
      background: '#faf9f6',
      foreground: '#25262b',
      card: '#f5f5f0',
      cardForeground: '#25262b',
      primary: '#343a46',
      primaryForeground: '#faf9f6',
      secondary: '#eeeee8',
      secondaryForeground: '#343a46',
      muted: '#eeeee8',
      mutedForeground: '#8e8e93',
      accent: '#eeeee8',
      accentForeground: '#343a46',
      destructive: '#dc3545',
      destructiveForeground: '#faf9f6',
      border: '#d5d5c8',
      input: '#e8e8e0',
      ring: '#b5b5b5',
    },
  },
  coolGray: {
    id: 'coolGray',
    name: 'Cool Gray',
    description: 'Modern Notion-style',
    colors: {
      background: '#f8f9fa',
      foreground: '#25262b',
      card: '#f1f3f5',
      cardForeground: '#25262b',
      primary: '#343a46',
      primaryForeground: '#f8f9fa',
      secondary: '#e9ecef',
      secondaryForeground: '#343a46',
      muted: '#e9ecef',
      mutedForeground: '#8e8e93',
      accent: '#e9ecef',
      accentForeground: '#343a46',
      destructive: '#dc3545',
      destructiveForeground: '#f8f9fa',
      border: '#d0d4d8',
      input: '#e5e8eb',
      ring: '#b5b5b5',
    },
  },
  lavender: {
    id: 'lavender',
    name: 'Lavender',
    description: 'Soft purple tones',
    colors: {
      background: '#faf8ff',
      foreground: '#25262b',
      card: '#f5f3ff',
      cardForeground: '#25262b',
      primary: '#7c3aed',
      primaryForeground: '#ffffff',
      secondary: '#ede9fe',
      secondaryForeground: '#5b21b6',
      muted: '#ede9fe',
      mutedForeground: '#8e8e93',
      accent: '#ede9fe',
      accentForeground: '#5b21b6',
      destructive: '#dc3545',
      destructiveForeground: '#ffffff',
      border: '#ddd6fe',
      input: '#e9e5fc',
      ring: '#a78bfa',
    },
  },
  mint: {
    id: 'mint',
    name: 'Mint',
    description: 'Fresh green accents',
    colors: {
      background: '#f7fef9',
      foreground: '#25262b',
      card: '#f0fdf4',
      cardForeground: '#25262b',
      primary: '#059669',
      primaryForeground: '#ffffff',
      secondary: '#d1fae5',
      secondaryForeground: '#065f46',
      muted: '#d1fae5',
      mutedForeground: '#8e8e93',
      accent: '#d1fae5',
      accentForeground: '#065f46',
      destructive: '#dc3545',
      destructiveForeground: '#ffffff',
      border: '#a7f3d0',
      input: '#d1fae5',
      ring: '#6ee7b7',
    },
  },
  vscode: {
    id: 'vscode',
    name: 'VS Code Light',
    description: 'Classic editor light',
    colors: {
      background: '#ffffff',
      foreground: '#24292e',
      card: '#f6f8fa',
      cardForeground: '#24292e',
      primary: '#0366d6',
      primaryForeground: '#ffffff',
      secondary: '#f6f8fa',
      secondaryForeground: '#24292e',
      muted: '#e1e4e8',
      mutedForeground: '#6a737d',
      accent: '#0366d6',
      accentForeground: '#ffffff',
      destructive: '#d73a49',
      destructiveForeground: '#ffffff',
      border: '#e1e4e8',
      input: '#fafbfc',
      ring: '#0366d6',
    },
  },
  intellij: {
    id: 'intellij',
    name: 'IntelliJ Light',
    description: 'Classic IDE light',
    colors: {
      background: '#ffffff',
      foreground: '#000000',
      card: '#f2f2f2',
      cardForeground: '#000000',
      primary: '#4b6eaf',
      primaryForeground: '#ffffff',
      secondary: '#f2f2f2',
      secondaryForeground: '#000000',
      muted: '#e8e8e8',
      mutedForeground: '#8c8c8c',
      accent: '#4b6eaf',
      accentForeground: '#ffffff',
      destructive: '#c7222c',
      destructiveForeground: '#ffffff',
      border: '#d4d4d4',
      input: '#f2f2f2',
      ring: '#4b6eaf',
    },
  },
  sky: {
    id: 'sky',
    name: 'Sky',
    description: 'Bright blue horizon',
    colors: {
      background: '#f0f9ff',
      foreground: '#25262b',
      card: '#e0f2fe',
      cardForeground: '#25262b',
      primary: '#0284c7',
      primaryForeground: '#ffffff',
      secondary: '#bae6fd',
      secondaryForeground: '#075985',
      muted: '#bae6fd',
      mutedForeground: '#8e8e93',
      accent: '#bae6fd',
      accentForeground: '#075985',
      destructive: '#dc3545',
      destructiveForeground: '#ffffff',
      border: '#7dd3fc',
      input: '#bae6fd',
      ring: '#38bdf8',
    },
  },
};

// Dark theme presets
export const DARK_THEME_PRESETS: Record<DarkThemePreset, ThemePreset> = {
  trueBlack: {
    id: 'trueBlack',
    name: 'True Black',
    description: 'OLED-friendly pure black',
    colors: {
      background: '#0a0a0a',
      foreground: '#fcfcfc',
      card: '#1a1a1a',
      cardForeground: '#fcfcfc',
      primary: '#ebebeb',
      primaryForeground: '#1a1a1a',
      secondary: '#2a2a2a',
      secondaryForeground: '#fcfcfc',
      muted: '#2a2a2a',
      mutedForeground: '#b5b5b5',
      accent: '#2a2a2a',
      accentForeground: '#fcfcfc',
      destructive: '#b91c1c',
      destructiveForeground: '#fcfcfc',
      border: 'rgba(255, 255, 255, 0.1)',
      input: 'rgba(255, 255, 255, 0.15)',
      ring: '#8e8e93',
    },
  },
  defaultDark: {
    id: 'defaultDark',
    name: 'Dark Gray',
    description: 'Balanced dark gray',
    colors: {
      background: '#252525',
      foreground: '#fcfcfc',
      card: '#353535',
      cardForeground: '#fcfcfc',
      primary: '#ebebeb',
      primaryForeground: '#353535',
      secondary: '#454545',
      secondaryForeground: '#fcfcfc',
      muted: '#454545',
      mutedForeground: '#b5b5b5',
      accent: '#454545',
      accentForeground: '#fcfcfc',
      destructive: '#b91c1c',
      destructiveForeground: '#fcfcfc',
      border: 'rgba(255, 255, 255, 0.1)',
      input: 'rgba(255, 255, 255, 0.15)',
      ring: '#8e8e93',
    },
  },
  deepBlue: {
    id: 'deepBlue',
    name: 'Deep Blue',
    description: 'Dark blue undertones',
    colors: {
      background: '#0f1419',
      foreground: '#e3e8ef',
      card: '#1a1f2e',
      cardForeground: '#e3e8ef',
      primary: '#60a5fa',
      primaryForeground: '#0f1419',
      secondary: '#1e293b',
      secondaryForeground: '#e3e8ef',
      muted: '#1e293b',
      mutedForeground: '#94a3b8',
      accent: '#1e293b',
      accentForeground: '#e3e8ef',
      destructive: '#ef4444',
      destructiveForeground: '#ffffff',
      border: 'rgba(96, 165, 250, 0.15)',
      input: 'rgba(255, 255, 255, 0.1)',
      ring: '#60a5fa',
    },
  },
  darkPurple: {
    id: 'darkPurple',
    name: 'Dark Purple',
    description: 'Rich purple hues',
    colors: {
      background: '#1a0f2e',
      foreground: '#f3e8ff',
      card: '#2a1f3d',
      cardForeground: '#f3e8ff',
      primary: '#a78bfa',
      primaryForeground: '#1a0f2e',
      secondary: '#3b2a54',
      secondaryForeground: '#f3e8ff',
      muted: '#3b2a54',
      mutedForeground: '#c4b5fd',
      accent: '#3b2a54',
      accentForeground: '#f3e8ff',
      destructive: '#f43f5e',
      destructiveForeground: '#ffffff',
      border: 'rgba(167, 139, 250, 0.15)',
      input: 'rgba(255, 255, 255, 0.1)',
      ring: '#a78bfa',
    },
  },
  forest: {
    id: 'forest',
    name: 'Forest',
    description: 'Deep green ambiance',
    colors: {
      background: '#0a1409',
      foreground: '#e8f5e9',
      card: '#1a2d19',
      cardForeground: '#e8f5e9',
      primary: '#4ade80',
      primaryForeground: '#0a1409',
      secondary: '#1e3a1c',
      secondaryForeground: '#e8f5e9',
      muted: '#1e3a1c',
      mutedForeground: '#86efac',
      accent: '#1e3a1c',
      accentForeground: '#e8f5e9',
      destructive: '#f87171',
      destructiveForeground: '#ffffff',
      border: 'rgba(74, 222, 128, 0.15)',
      input: 'rgba(255, 255, 255, 0.1)',
      ring: '#4ade80',
    },
  },
  vscodeDark: {
    id: 'vscodeDark',
    name: 'VS Code Dark',
    description: 'Classic editor dark',
    colors: {
      background: '#1e1e1e',
      foreground: '#d4d4d4',
      card: '#252526',
      cardForeground: '#d4d4d4',
      primary: '#007acc',
      primaryForeground: '#ffffff',
      secondary: '#2d2d30',
      secondaryForeground: '#cccccc',
      muted: '#2d2d30',
      mutedForeground: '#858585',
      accent: '#007acc',
      accentForeground: '#ffffff',
      destructive: '#f48771',
      destructiveForeground: '#ffffff',
      border: 'rgba(255, 255, 255, 0.1)',
      input: 'rgba(255, 255, 255, 0.1)',
      ring: '#007acc',
    },
  },
  dracula: {
    id: 'dracula',
    name: 'Dracula',
    description: 'Purple & pink accents',
    colors: {
      background: '#282a36',
      foreground: '#f8f8f2',
      card: '#383a59',
      cardForeground: '#f8f8f2',
      primary: '#bd93f9',
      primaryForeground: '#282a36',
      secondary: '#44475a',
      secondaryForeground: '#f8f8f2',
      muted: '#44475a',
      mutedForeground: '#6272a4',
      accent: '#ff79c6',
      accentForeground: '#282a36',
      destructive: '#ff5555',
      destructiveForeground: '#282a36',
      border: 'rgba(189, 147, 249, 0.15)',
      input: 'rgba(248, 248, 242, 0.1)',
      ring: '#bd93f9',
    },
  },
  darkTeal: {
    id: 'darkTeal',
    name: 'Dark Teal',
    description: 'Cool cyan depths',
    colors: {
      background: '#0a1414',
      foreground: '#e8ffff',
      card: '#14292a',
      cardForeground: '#e8ffff',
      primary: '#2dd4bf',
      primaryForeground: '#0a1414',
      secondary: '#1e3a3a',
      secondaryForeground: '#e8ffff',
      muted: '#1e3a3a',
      mutedForeground: '#5eead4',
      accent: '#1e3a3a',
      accentForeground: '#e8ffff',
      destructive: '#f87171',
      destructiveForeground: '#ffffff',
      border: 'rgba(45, 212, 191, 0.15)',
      input: 'rgba(255, 255, 255, 0.1)',
      ring: '#2dd4bf',
    },
  },
};
