name: Desktop Build

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-desktop:
    name: Build Desktop Apps
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win
            artifact: exe
          - os: macos-latest
            platform: mac
            artifact: dmg
          - os: ubuntu-latest
            platform: linux
            artifact: AppImage

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build web app
        run: pnpm build

      - name: Install desktop dependencies
        run: cd apps/desktop && npm install

      - name: Build desktop app
        run: cd apps/desktop && npm run build:${{ matrix.platform }}

      - name: List built files
        run: |
          echo "=== Contents of apps/desktop/dist ==="
          ls -la apps/desktop/dist/ || echo "No dist directory"
          find apps/desktop -name "*.exe" -o -name "*.dmg" -o -name "*.AppImage" || echo "No executables found"
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: typelets-${{ matrix.platform }}
          path: apps/desktop/dist/
          retention-days: 90

  attach-assets:
    name: Attach Desktop Assets
    needs: build-desktop
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: List downloaded artifacts
        run: find release-artifacts -type f -name "*" | head -20

      - name: Attach assets to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            release-artifacts/**/*.exe
            release-artifacts/**/*.dmg
            release-artifacts/**/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}