name: Desktop Build

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-desktop:
    name: Build Desktop Apps
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win
            artifact: exe
          - os: macos-latest
            platform: mac
            artifact: dmg
          - os: ubuntu-latest
            platform: linux
            artifact: AppImage

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build web app
        run: pnpm build

      - name: Install desktop dependencies
        run: cd apps/desktop && npm install

      - name: Build desktop app
        run: cd apps/desktop && npm run build:${{ matrix.platform }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: typelets-${{ matrix.platform }}
          path: |
            apps/desktop/dist/*.exe
            apps/desktop/dist/*.dmg
            apps/desktop/dist/*.AppImage
            apps/desktop/dist/*.deb
            apps/desktop/dist/*.rpm
          retention-days: 90

  attach-assets:
    name: Attach Desktop Assets
    needs: build-desktop
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: Attach assets to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            release-artifacts/typelets-win/*.exe
            release-artifacts/typelets-mac/*.dmg
            release-artifacts/typelets-linux/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}